//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.InformationForEmployees = new HashSet<InformationForEmployees>();
        }
    
        public int kod_employee { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patrinymic { get; set; }
        public int id_role { get; set; }
        public Nullable<int> nomer { get; set; }
        public Nullable<int> password { get; set; }
        public string id_employees { get; set; }
        public string photo { get; set; }
    
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformationForEmployees> InformationForEmployees { get; set; }
    }
}
