//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationForEmployees
    {
        public int kod_information { get; set; }
        public int kod_employees { get; set; }
        public string information { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
