//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscribers()
        {
            this.Applications = new HashSet<Applications>();
            this.SubscriberServices = new HashSet<SubscriberServices>();
        }
    
        public int kod_subscribers { get; set; }
        public string subscriber_number { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public int kod_pola { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string place_of_residence { get; set; }
        public int kod_district { get; set; }
        public string addres_of_residence { get; set; }
        public string series_passport_number { get; set; }
        public string department_code { get; set; }
        public string issued_by { get; set; }
        public System.DateTime date_of_issue { get; set; }
        public string contract_number { get; set; }
        public System.DateTime date_conclusion_contract { get; set; }
        public int kod_contract_type { get; set; }
        public string reason_for_termination { get; set; }
        public int personal_account { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string rent { get; set; }
        public int equipment_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual ContractTypes ContractTypes { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Pols Pols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberServices> SubscriberServices { get; set; }
    }
}
