//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberServices
    {
        public int kod { get; set; }
        public int kod_subscriber { get; set; }
        public int kod_serveces { get; set; }
        public Nullable<System.DateTime> connection_date { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Subscribers Subscribers { get; set; }
    }
}
