//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableEquipment
    {
        public int EquipmentID { get; set; }
        public string EquipmentSerialNumber { get; set; }
        public string EquipmentName { get; set; }
    }
}
